import uiautomation
class FrameRates:
    def __init__(self):
        self.framerate=uiautomation.EditControl(AutomationId='mainAppWidget.stackedWidget_main.page_2.widget_7.widget_40.stackedWidget_RightBar.page_13.widget_22.widget_43.LithiumDectorWidgetClass.widget.widget_6.widget_2.lineEdit_DetFrame')
        self.pixelmerge1=uiautomation.RadioButtonControl(AutomationId='mainAppWidget.stackedWidget_main.page_2.widget_7.widget_40.stackedWidget_RightBar.page_13.widget_22.widget_43.LithiumDectorWidgetClass.widget.widget_6.widget_3.widget_5.pushButton_Binning1')
        self.pixelmerge2=uiautomation.RadioButtonControl(AutomationId='mainAppWidget.stackedWidget_main.page_2.widget_7.widget_40.stackedWidget_RightBar.page_33.widget_22.widget_43.LithiumDectorWidgetClass.widget.widget_6.widget_3.widget_5.pushButton_Binning2')
        self.pixelmerge3=uiautomation.RadioButtonControl(AutomationId='mainAppWidget.stackedWidget_main.page_2.widget_7.widget_40.stackedWidget_RightBar.page_33.widget_22.widget_43.LithiumDectorWidgetClass.widget.widget_6.widget_3.widget_5.pushButton_Binning3')
        self.apply=uiautomation.ButtonControl(AutomationId='mainAppWidget.stackedWidget_main.page_2.widget_7.widget_40.stackedWidget_RightBar.page_33.widget_22.widget_43.LithiumDectorWidgetClass.widget.widget_7.pushButton_setDynaParam')
        self.comboBoxButton=uiautomation.ComboBoxControl(AutomationId='mainAppWidget.stackedWidget_main.page_2.widget_7.widget_40.stackedWidget_RightBar.page_13.widget_22.widget_43.LithiumDectorWidgetClass.widget.widget_6.widget_4.comboBox_PGA')
        self.pga0Button=uiautomation.ListItemControl(Name='PGA0')
        self.pga1Button=uiautomation.ListItemControl(Name='PGA1')
        self.pga2Button=uiautomation.ListItemControl(Name='PGA2')
        self.pga3Button=uiautomation.ListItemControl(Name='PGA3')
        self.pga4Button=uiautomation.ListItemControl(Name='PGA4')
        self.pga5Button=uiautomation.ListItemControl(Name='PGA5')
        self.pga6Button=uiautomation.ListItemControl(Name='PGA6')
        self.pga7Button=uiautomation.ListItemControl(Name='PGA7')
        self.pga8Button=uiautomation.ListItemControl(Name='PGA8')
        self.pga9Button=uiautomation.ListItemControl(Name='PGA9')
    def framerates(self,framerate):
        self.framerate.GetValuePattern().SetValue(' ')
        self.framerate.GetValuePattern().SetValue(framerate)
    #这些备用
    def pixelMerges1(self):
        self.pixelmerge1.Click()
        self.comboBoxButton.Click()
        self.pga3Button.Click()
        # self.comboBoxButton.Click()
        # self.pixelmerge1.Click()
        # self.pga3Button.Click()
        # self.comboBoxButton.Click()
        # self.pixelmerge1.Click()
        # self.pga2Button.Click()
        # self.comboBoxButton.Click()
        # self.pixelmerge1.Click()
        # self.pga3Button.Click()
        # self.comboBoxButton.Click()
        # self.pixelmerge1.Click()
        # self.pga4Button.Click()
        # self.comboBoxButton.Click()
        # self.pixelmerge1.Click()
        # self.pga5Button.Click()
        # self.comboBoxButton.Click()
        # self.pixelmerge1.Click()
        # self.pga6Button.Click()
        # self.comboBoxButton.Click()
        # self.pixelmerge1.Click()
        # self.pga7Button.Click()
        # self.comboBoxButton.Click()
        # self.pixelmerge1.Click()
        # self.pga8Button.Click()
        # self.comboBoxButton.Click()
        # self.pixelmerge1.Click()
        # self.pga9Button.Click()
    def pixelMerges2(self):
        self.pixelmerge2.Click()
        self.comboBoxButton.Click()
        self.pga0Button.Click()
        self.comboBoxButton.Click()
        self.pixelmerge2.Click()
        self.pga2Button.Click()
        self.comboBoxButton.Click()
        self.pixelmerge2.Click()
        self.pga2Button.Click()
        self.comboBoxButton.Click()
        self.pixelmerge2.Click()
        self.pga3Button.Click()
        self.comboBoxButton.Click()
        self.pixelmerge2.Click()
        self.pga4Button.Click()
        self.comboBoxButton.Click()
        self.pixelmerge2.Click()
        self.pga5Button.Click()
        self.comboBoxButton.Click()
        self.pixelmerge2.Click()
        self.pga6Button.Click()
        self.comboBoxButton.Click()
        self.pixelmerge2.Click()
        self.pga7Button.Click()
        self.comboBoxButton.Click()
        self.pixelmerge2.Click()
        self.pga8Button.Click()
        self.comboBoxButton.Click()
        self.pixelmerge2.Click()
        self.pga9Button.Click()
    def pixelMerges3(self):
        self.pixelmerge3.Click()
        self.comboBoxButton.Click()
        self.pga0Button.Click()
        self.comboBoxButton.Click()
        self.pixelmerge3.Click()
        self.pga3Button.Click()
        self.comboBoxButton.Click()
        self.pixelmerge3.Click()
        self.pga2Button.Click()
        self.comboBoxButton.Click()
        self.pixelmerge3.Click()
        self.pga3Button.Click()
        self.comboBoxButton.Click()
        self.pixelmerge3.Click()
        self.pga4Button.Click()
        self.comboBoxButton.Click()
        self.pixelmerge3.Click()
        self.pga5Button.Click()
        self.comboBoxButton.Click()
        self.pixelmerge3.Click()
        self.pga6Button.Click()
        self.comboBoxButton.Click()
        self.pixelmerge3.Click()
        self.pga7Button.Click()
        self.comboBoxButton.Click()
        self.pixelmerge3.Click()
        self.pga8Button.Click()
        self.comboBoxButton.Click()
        self.pixelmerge3.Click()
        self.pga9Button.Click()
# FrameRates().framerates('30')
# FrameRates().pixelMerges1()
